/**
    * @description : This is a POJO to represent the product-country-charge information
    * @author      : revathyharidas@gmail.com
*/
public class CardInfo {
    public String card_type {get;set;}
    public String country {get;set;}
    public String cost_per_calender_month {get;set;}
    public String atm_fee_in_other_currencies {get;set;}
    public String card_replacement_cost {get;set;}
}